/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-03-28 21:54:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import net.etfbl.ip.AppUser;
import net.etfbl.ip.beans.AppUserBean;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("net.etfbl.ip.AppUser");
    _jspx_imports_classes.add("net.etfbl.ip.beans.AppUserBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
      net.etfbl.ip.beans.AppUserBean appUserBean = null;
      synchronized (application) {
        appUserBean = (net.etfbl.ip.beans.AppUserBean) _jspx_page_context.getAttribute("appUserBean", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (appUserBean == null){
          appUserBean = new net.etfbl.ip.beans.AppUserBean();
          _jspx_page_context.setAttribute("appUserBean", appUserBean, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      net.etfbl.ip.AppUser appUser = null;
      synchronized (session) {
        appUser = (net.etfbl.ip.AppUser) _jspx_page_context.getAttribute("appUser", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (appUser == null){
          appUser = new net.etfbl.ip.AppUser();
          _jspx_page_context.setAttribute("appUser", appUser, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      out.write('	');
      net.etfbl.ip.beans.MessageBean messageBean = null;
      synchronized (application) {
        messageBean = (net.etfbl.ip.beans.MessageBean) _jspx_page_context.getAttribute("messageBean", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (messageBean == null){
          messageBean = new net.etfbl.ip.beans.MessageBean();
          _jspx_page_context.setAttribute("messageBean", messageBean, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      net.etfbl.ip.Message message = null;
      synchronized (session) {
        message = (net.etfbl.ip.Message) _jspx_page_context.getAttribute("message", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (message == null){
          message = new net.etfbl.ip.Message();
          _jspx_page_context.setAttribute("message", message, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("appUser"), "username", request.getParameter("username"), request, "username", false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("appUser"), "password", request.getParameter("password"), request, "password", false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");

	if (request.getParameter("submit") != null) {
		AppUser u = appUserBean.loginUser(appUser.getUsername(), appUser.getPassword());
		if (u != null) {
			u.setFirstName(u.getFirstName());
			u.setLastName(u.getLastName());
			u.setEmail(u.getEmail());
			u.setLoggedIn(true);
			session.setAttribute("notification", "");
			response.sendRedirect("messages.jsp");
		} else {
			session.setAttribute("notification", "Unijeli ste neispravno korisni&#269;ko ime ili lozinku.");
			//u.setLoggedIn(false);
		}
	} else {
		session.setAttribute("notification", "");
	}

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/style.css\"></link>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>ETFBL_IP User Support</h1>\r\n");
      out.write("<hr/>\r\n");
      out.write("	<h2>Prijava na sistem</h2>\r\n");
      out.write("	<form method=\"POST\" action=\"login.jsp\">\r\n");
      out.write("		Korisni&#269;ko ime<br /> <input type=\"text\" name=\"username\"\r\n");
      out.write("			id=\"username\" /><br /><br /> Lozinka <br /> <input type=\"password\"\r\n");
      out.write("			name=\"password\" id=\"password\" /><br /> <br /><input type=\"submit\"\r\n");
      out.write("			value=\"Prijavi me\" name=\"submit\" /><br />\r\n");
      out.write("		<h3>");
      out.print(session.getAttribute("notification").toString());
      out.write("</h3>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
